### ISSUE TITLE
Options that don't appear to work in Sublime 3

### ISSUE THREAD

**Issue by jrhorn424** [netatoo/phoenix-theme#30]
Hi! Great theme. Having a few issues on Sublime 3. The following options no longer appear to work:

```
    "phoneix_color_blue": true, // or any other color
    "phoenix_color_expanded_folder": true,
    "phoenix_highlight_current_tab": true,
```

The following _do_ work, quite pleasantly:

```
    "phoenix_dirty_bottom_bar": true,
    "phoenix_eighties": true,
```

Thanks for the theme! Hope this is an easy fix.

**Comment by daslicht** [comment]
Phoenix Dark Orange.tmTheme is not sufficient ?

**Comment by Fatbat** [comment]
No…

 

"color_scheme": "Packages/Theme - Phoenix/Color Scheme/Phoenix Dark Orange.tmTheme",

    "ignored_packages":

 

is not the theme, it’s the color scheme. A theme is different from a colour scheme. One changes the interface, the tabs, icons, the way the files and folders look, the size of things, whereas the other simply changes the colors of your code. You need to use both and can customize your color scheme separately (for example, I do not use the color schemes that come with Pheonix, I use a modified version of Twilight with Phoenix Dark). So add…

 

"theme": "Phoenix Dark.sublime-theme",

 

To your Settings – User file and you should be good to go.

 

Regards,

Brad

**Comment by daslicht** [comment]
Thank you !
